const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const Tail = require('tail').Tail;

const app = express();
const PORT = process.env.PORT || 5000; // Thay đổi cổng thành 5000 để nhường 8000 cho Python FastAPI

// Cấu hình CORS sinh tử (Yêu cầu 2 của Giai đoạn 2)
app.use(cors({
    origin: ['http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:3000'],
    methods: ['GET', 'POST', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization']
}));

// Yêu cầu 2: Sử dụng path.join an toàn
const METRICS_FILE = path.join(__dirname, '..', 'logs', 'trading', 'advanced_quant_metrics.json');
const STREAM_LOG_FILE = path.join(__dirname, '..', 'logs', 'trading', 'training_stream.log');

// Endpoint Placeholder: Read actual market snapshots generated by the Python Engine
app.get('/api/v1/market/top_movers', (req, res) => {
    const ASSET_SNAPSHOT_FILE = path.join(__dirname, '..', 'logs', 'trading', 'asset_snapshot.json');
    if (fs.existsSync(ASSET_SNAPSHOT_FILE)) {
        try {
            const data = JSON.parse(fs.readFileSync(ASSET_SNAPSHOT_FILE, 'utf8'));
            return res.json({ status: 'success', data: data });
        } catch (e) {
            console.error("Error reading snapshot", e);
        }
    }
    // Fallback if python engine hasn't dumped snapshot
    res.json({ status: 'success', data: [] });
});

// Endpoint 1: 70+ Quant Metrics JSON
app.get('/api/quant/metrics', (req, res) => {
    try {
        if (!fs.existsSync(METRICS_FILE)) {
            return res.status(404).json({ status: 'error', message: 'Metrics not found. Run backend backtest first.' });
        }
        const data = fs.readFileSync(METRICS_FILE, 'utf8');
        res.json(JSON.parse(data));
    } catch (error) {
        res.status(500).json({ status: 'error', message: error.message });
    }
});

// Endpoint 2: SSE - Training Stream Log Tracker
app.get('/api/quant/training-stream', (req, res) => {
    // SSE Setup Headers
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    
    res.write('data: {"status": "connected"}\n\n');

    if (!fs.existsSync(STREAM_LOG_FILE)) {
        // Create if not exists so Tail doesn't crash
        fs.writeFileSync(STREAM_LOG_FILE, '');
    }

    // Use Tail to watch the log file without tying up Node JS thread
    const tail = new Tail(STREAM_LOG_FILE, { fromBeginning: false });

    tail.on("line", function(data) {
        if (data.trim() !== '') {
            res.write(`data: ${JSON.stringify({ log: data })}\n\n`);
        }
    });

    tail.on("error", function(error) {
        console.error('Tail Error:', error);
    });

    req.on('close', () => {
        tail.unwatch();
    });
});

app.listen(PORT, () => {
    console.log(`AlphaQuant Express Backend running on http://127.0.0.1:${PORT}`);
});
